#!/bin/bash

REQUIRED_FILE="./ftc"

if [ ! -f ${REQUIRE_FILE} ];
then
	echo "⚠️  Executable ${REQUIRED_FILE} not found."
	exit 1
fi

function test_no_mime_and_size () {
	if [ ! "$(./ftc "$1" -mime "$2" -size "$3")" == "$(find "$1" -type f -size "$3" -regex "$4")" ];
	then
        echo "🔴 Test of no file of mime \"$2\" and size \"$3\" failed."
		echo "$(./ftc "$1" -mime "$2" -size "$3")"
		exit 1
	else
        echo "✅ Test of no file of  mime and size succeeded (mime: \"$2\", size: \"$3\")."
	fi
}

test_no_mime_and_size "arbre" "text/plain" "-75c" ".*.txt"

function test_unique_mime_and_size () {
	if [ ! "$(./ftc "$1" -mime "$2" -size "$3")" == "$(find "$1" -type f -size "$3" -regex "$4")" ];
	then
        echo "🔴 Test of unique file of mime \"$2\" and size \"$3\" failed."
		echo "$(./ftc "$1" -mime "$2" -size "$3")"
		exit 1
	else
        echo "✅ Test of unique file of mime and size succeeded (mime: \"$2\", size: \"$3\")."
	fi
}

test_unique_mime_and_size "arbre" "text/plain" "-100c" ".*.txt"

function test_mult_mime_and_size () {
	if [ ! "$(./ftc "$1" -mime "$2" -size "$3" | wc -l)" == "$(find "$1" -type f -size "$3" -regex "$4" | wc -l)" ];
	then
        echo "🔴 Test of multiple files of mime \"$2\" and size \"$3\" failed."
		echo "$(./ftc "$1" -mime "$2" -size "$3")"
		exit 1
	else
        echo "✅ Test of multiple files of mime and size succeeded (mime: \"$2\", size: \"$3\")."
	fi
}

test_mult_mime_and_size "arbre" "text/plain" "-200k" ".*.txt"
