#!/bin/bash

REQUIRED_FILE="./ftc"

if [ ! -f ${REQUIRED_FILE} ] 
then
    echo "⚠️ Executable ${REQUIRED_FILE} not found."
    exit 1
fi

function test_find_perm () {
    if [ ! "$(./ftc $1 "-perm" $2 | wc -l)" == "$(find $1 "-perm" $2 "-type" "f" | wc -l)" ];
    then
        echo "🔴 Test of perm failed for \"$2\""
        #exit 1
    else
        echo "✅ Test of perm succeeded (string: \"$2\")."
    fi
}

test_find_perm "arbre" "700"
test_find_perm "arbre" "001"

function test_find_perm_detailed () {
    if [ ! "$(./ftc $1 "-perm" $2)" == "$(find $1 "-perm" $2 "-type" "f")" ];
    then
        echo "🔴 Test of perm failed for \"$2\""
    else
        echo "✅ Test of perm succeeded (string: \"$2\")."
    fi
}

test_find_perm_detailed "." "000"
