#!/bin/bash

REQUIRED_FILE="./ftc"

if [ ! -f ${REQUIRED_FILE} ] 
then
    echo "⚠️ Executable ${REQUIRED_FILE} not found."
    exit 1
fi

function test_find_grep () {
    if [ ! "$(./ftc $1 "-ctc" $2)" 2>/dev/null == $3 ];
    then
        echo "🔴 Test of \"catch the cat\" failed for \"$2\""
        #exit 1
    else
        echo "✅ Test of \"catch the cat\" succeeded (string: \"$2\")."
    fi
}

test_find_grep "arbre" "audience do pipoulapi" "arbre/sell/foreign.mp3"

function test_find_grep_nb () {
    if [ ! "$(./ftc $1 "-ctc" $2 2>/dev/null | wc -l)" == $3 ];
    then
        echo "🔴 Test of \"catch the cat\" failed for \"$2\""
    else
        echo "✅ Test of \"catch the cat\" succeeded (string: \"$2\")."
    fi
}

test_find_grep "arbre" "Property current include" "2"

function test_find_grep_regex () {
    if [ ! "$(./ftc $1 "-ctc" $2)"2>/dev/null == $3 ];
    then
        echo "🔴 Test of \"catch the cat\" with regex failed for \"$2\""
    else
        echo "✅ Test of \"catch the cat\" with regex succeeded (regex: \"$2\")."
    fi
}

test_find_grep "arbre" "than star.*" "4"