#!/bin/bash

REQUIRED_FILE="./ftc"

if [ ! -f ${REQUIRED_FILE} ] 
then
    echo "⚠️ Executable ${REQUIRED_FILE} not found."
    exit 1
fi

function test_find_mime () {
    if [ ! "$(./ftc "$1" "-mime" "$2")" == $3 ];
    then
        echo "🔴 Test of the mime type failed for type \"$2\""
        echo "$(./ftc "$1" "-mime" "$2")"
        echo "$(find "$1" "-name" "$3")"
    else
        echo "✅ Test of find with mime type succeeded (type: \"$2\")."
    fi
}


test_find_mime "arbre/economic/player/his/a/" "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" "arbre/economic/player/his/a/buy.xlsx"
