#!/bin/bash

REQUIRED_FILE="./ftc"

if [ ! -f ${REQUIRED_FILE} ] 
then
    echo "⚠️ Executable ${REQUIRED_FILE} not found."
    exit 1
fi

function test_find_name () {
    if [ ! "$(./ftc "$1" "-name" "$2")" == "$3" ];
    then
        echo "🔴 Test of find with name failed for file \"$2\""
    else
        echo "✅ Test of find with name succeeded (file: \"$2\")."
    fi
}


test_find_name "arbre" "unit.json" "arbre/think/sea/company/lawyer/unit.json"
test_find_name "arbre" "hand.mov" "arbre/yourself/nature/Republican/them/hand.mov"

