#!/bin/bash

REQUIRED_FILE="./ftc"

if [ ! -f ${REQUIRED_FILE} ] 
then
    echo "⚠️ Executable ${REQUIRED_FILE} not found."
    exit 1
fi

function test_find_exact_size () {
    if [ ! "$(./ftc $1 "-size" $2)" == "$(find $1 "-size" $2)" ];
    then
        echo "🔴 Test of find with exact size failed for param \"$2 $3\""
        echo "$(./ftc $1 "-size" $2)"
    else
        echo "✅ Test of find with exact size succeeded (file: \"$2\")."
    fi
}

test_find_exact_size "arbre" "27c" "arbre/tree/character/kind/ball.wav"

function test_find_size () {
    if [ ! "$(./ftc $1 "-size" $2 | wc -l)" == "$3" ];
    then
        echo "🔴 Test of find with size failed for param \"$2 $3\""
    else
        echo "✅ Test of find with size succeeded (file: \"$2 $3\")."
    fi
}


test_find_size "arbre" "-75c" "15"
test_find_size "arbre" "+9k" "510"