#!/bin/bash

REQUIRED_FILE="./ftc"

if [ ! -f ${REQUIRED_FILE} ] 
then
    echo "⚠️ Executable ${REQUIRED_FILE} not found."
    exit 1
fi

function test_find_regex_exact () {
    if [ ! "$(./ftc $1 "-name" $2 | wc -l)" == $3 ];
    then
        echo "🔴 Test of regex failed for \"$2\""
    else
        echo "✅ Test of find with regex succeeded (regex: \"$2\")."
    fi
}

test_find_regex_exact "arbre/" "*st.gif" "arbre/put/least.gif"

function test_find_regex () {
    if [ ! "$(./ftc $1 "-name" $2 | wc -l)" == $3 ];
    then
        echo "🔴 Test of regex failed for \"$2\""
    else
        echo "✅ Test of find with regex succeeded (regex: \"$2\")."
    fi
}


test_find_regex 
test_find_regex "arbre/" "*[^a-s]ty.mp3" "1"
test_find_regex "arbre/" "*[^a-u]ty.mp3" "0"
