#!/bin/bash

REQUIRED_FILE="./ftc"

if [ ! -f ${REQUIRED_FILE} ] 
then
    echo "⚠️ Executable ${REQUIRED_FILE} not found."
    exit 1
fi

function test_find_date () {
    touch $2
    if [ ! "$(./ftc $1 "-date" $2)" == "$(find $1 "-mmin" $3)" ];
    then
        echo "🔴 Test of the file tree failed for date param \"$2\""
        echo "$(./ftc $1 -date $2)"
    else
        echo "✅ Test of find with name succeeded (date: \"$3\")."
    fi
}

test_find_date "arbre" "-2m" "-2" 

function test_find_date_several () {
    touch $2
    if [ ! "$(./ftc $1 -date $2 | wc -l)" == "$(find $1 "-mmin" $3 | wc -l)" ];
    then
        echo "🔴 Test of the file tree failed for date param \"$2\""
        echo "$(./ftc $1 -date $2 | wc -l)"
    else
        echo "✅ Test of find with name succeeded (date: \"$3\")."
    fi
}

test_find_date_several "arbre" "-4m" "-4"