#!/bin/bash

REQUIRED_FILE="./ftc"

if [ ! -f ${REQUIRED_FILE} ] 
then
    echo "⚠️ Executable ${REQUIRED_FILE} not found."
    exit 1
fi

function test_parkour () {
    if [ ! "$(./ftc "$1" | wc -l)" == "$(find "$1" -type d | wc -l)" ];
    then
        echo "🔴 Test of the file tree failed for dir \"$1\""
        echo "$(./ftc "$1")"
    else
        echo "✅ Test of the file tree succeeded (dir: \"$1\")."
    fi
}


test_parkour "arbre"
test_parkour "arbre/economic/old/officer/"