name: projet_sys22/tests

on: [push]

jobs:
  make-test:
    runs-on: ubuntu-latest
    container:
      image: racouchot/projet_sys22
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build tests files
        run: |
          mkdir tests
          cp /tests/* tests
          mkdir arbre
          cp -r /arbre/* arbre

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: projet_sys22
          path: |
            /tests
            /arbre

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check repository
        uses: actions/checkout@v3

      - name: Build executable
        run: make

  check-test-build:
    runs-on: ubuntu-latest
    needs: make-test
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: projet_sys22

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Check test build
        run: ls -al ./tests
