name: projet_sys22/tests

on: [push]

jobs:
  full-option-job:
    runs-on: ubuntu-latest
    container:
      image: yewolf/projet_sys22
    steps:
      - name: Check repository
        uses: actions/checkout@v3

      - name: Build executable
        run: make

      - name: Build tests files
        run: |
          mkdir tests
          cp /tests/* tests
          mkdir arbre
          cp -r /arbre/* arbre

      - name: Check test build
        run: ./tests/file_exist ./ftc
