name: projet_sys22/tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: yewolf/projet_sys22
    steps:
      - name: Check repository
        uses: actions/checkout@v3

      - name: Build tests files
        run: |
          mkdir arbre
          cp -r /arbre/* arbre

      - name: Build executable
        run: make

      - name: Check test build
        run: ./tests/file_exist ./ftc

  test-args:
    runs-on: ubuntu-latest
    needs: build
    container:
      image: yewolf/projet_sys22
    steps:
      - name: Check repository
        uses: actions/checkout@v3

      - name: Build tests files
        run: |
          mkdir arbre
          cp -r /arbre/* arbre

      - name: Build executable
        run: make

      - name: Check test args
        run: ./tests/test_args

  test-parkour:
    runs-on: ubuntu-latest
    needs: build
    container:
      image: yewolf/projet_sys22
    steps:
      - name: Check repository
        uses: actions/checkout@v3

      - name: Build tests files
        run: |
          mkdir arbre
          cp -r /arbre/* arbre

      - name: Build executable
        run: make

      - name: Check test parkour
        run: ./tests/test_parkour
  
  test-name:
    runs-on: ubuntu-latest
    needs: build
    container:
      image: yewolf/projet_sys22
    steps:
      - name: Check repository
        uses: actions/checkout@v3

      - name: Build tests files
        run: |
          mkdir arbre
          cp -r /arbre/* arbre

      - name: Build executable
        run: make
      
      - name: Check test name
        run: ./tests/test_name
  
  test-size:
    runs-on: ubuntu-latest
    needs: build
    container:
      image: yewolf/projet_sys22
    steps:
      - name: Check repository
        uses: actions/checkout@v3

      - name: Build tests files
        run: |
          mkdir arbre
          cp -r /arbre/* arbre

      - name: Build executable
        run: make
      
      - name: Check test size
        run: ./tests/test_size
  
  test-date:
    runs-on: ubuntu-latest
    needs: build
    container:
      image: yewolf/projet_sys22
    steps:
      - name: Check repository
        uses: actions/checkout@v3

      - name: Build tests files
        run: |
          mkdir arbre
          cp -r /arbre/* arbre

      - name: Build executable
        run: make

      - name: Check test date
        run: ./tests/test_date
  
  test-regex:
    runs-on: ubuntu-latest
    needs: build
    container:
      image: yewolf/projet_sys22
    steps:
      - name: Check repository
        uses: actions/checkout@v3

      - name: Build tests files
        run: |
          mkdir arbre
          cp -r /arbre/* arbre

      - name: Build executable
        run: make

      - name: Check test regex
        run: ./tests/test_regex

  test-mime:
    runs-on: ubuntu-latest
    needs: build
    container:
      image: yewolf/projet_sys22
    steps:
      - name: Check repository
        uses: actions/checkout@v3

      - name: Build tests files
        run: |
          mkdir arbre
          cp -r /arbre/* arbre

      - name: Build executable
        run: make

      - name: Check test mime
        run: ./tests/test_mime
  
  test-grep:
    runs-on: ubuntu-latest
    needs: build
    container:
      image: yewolf/projet_sys22
    steps:
      - name: Check repository
        uses: actions/checkout@v3

      - name: Build tests files
        run: |
          mkdir arbre
          cp -r /arbre/* arbre

      - name: Build executable
        run: make
      
      - name: Check test grep
        run: ./tests/test_grep

  test-dir:
    runs-on: ubuntu-latest
    needs: build
    container:
      image: yewolf/projet_sys22
    steps:
      - name: Check repository
        uses: actions/checkout@v3

      - name: Build tests files
        run: |
          mkdir arbre
          cp -r /arbre/* arbre

      - name: Build executable
        run: make
      
      - name: Check test dir
        run: ./tests/test_dir

  test-perm:
    runs-on: ubuntu-latest
    needs: build
    container:
      image: yewolf/projet_sys22
    steps:
      - name: Check repository
        uses: actions/checkout@v3

      - name: Build tests files
        run: |
          mkdir arbre
          cp -r /arbre/* arbre

      - name: Build executable
        run: make
      
      - name: Check test perm
        run: ./tests/test_perm