name: projet_sys22/tests

on: [push]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    container:
      image: yewolf/projet_sys22
    steps:
      - name: Check repository
        uses: actions/checkout@v3

      - name: Build tests files
        run: |
          mkdir arbre
          cp -r /arbre/* arbre

      - name: Build executable
        run: make

      - name: Check test build
        run: ./tests/file_exist ./ftc

      - name: Check test args
        run: ./tests/test_args
      
      - name: Check test parkour
        run: ./tests/test_parkour
      
      - name: Check test name
        run: ./tests/test_name
      
      - name: Check test size
        run: ./tests/test_size

      - name: Check test date
        run: ./tests/test_date

      - name: Check test regex
        run: ./tests/test_regex

      - name: Check test mime
        run: ./tests/test_mime
      
      - name: Check test grep
        run: ./tests/test_grep
      
      - name: Check test dir
        run: ./tests/test_dir
      
      - name: Check test perm
        run: ./tests/test_perm