name: projet_sys22/tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: thibaultcne/projet_sys22
    steps:
      - name: Check repository
        uses: actions/checkout@v3

      - name: Build executable
        run: make

      - name: Build tests files
        run: |
          mkdir arbre
          mkdir tests
          cp -r /arbre/* arbre
          cp -r /tests/* tests

      - name: Check test build
        run: ./tests/file_exist ./ftc

  retrive-image:
    runs-on: ubuntu-latest
    container:
      image: gl-registry.telecomnancy.univ-lorraine.fr/christophe.bouthier/rs2022-dockertest
    steps:
      - name: Build tests files
        run: |
          mkdir arbre
          mkdir tests
          cp -r /arbre/* arbre
          cp -r /tests/* tests

      - name: Download
        uses: actions/upload-artifact@v3
        with:
          path: |
            tests
            arbre

  test-args:
    runs-on: ubuntu-latest
    container:
      image: thibaultcne/projet_sys22
    needs: build
    steps:
      - name: Check repository
        uses: actions/checkout@v3

      - name: Build executable
        run: make
      
      - name: Build tests files
        run: |
          mkdir arbre
          mkdir tests
          cp -r /arbre/* arbre
          cp -r /tests/* tests

      - name: Check test args
        run: ./tests/test_args

  test-parkour:
    runs-on: ubuntu-latest
    container:
      image: thibaultcne/projet_sys22
    needs: build
    steps:
      - name: Check repository
        uses: actions/checkout@v3

      - name: Build executable
        run: make
      
      - name: Build tests files
        run: |
          mkdir arbre
          mkdir tests
          cp -r /arbre/* arbre
          cp -r /tests/* tests

      - name: Check test parkour
        run: ./tests/test_parkour
  
  test-name:
    runs-on: ubuntu-latest
    container:
      image: thibaultcne/projet_sys22
    needs: build
    steps:
      - name: Check repository
        uses: actions/checkout@v3

      - name: Build executable
        run: make
      
      - name: Build tests files
        run: |
          mkdir arbre
          mkdir tests
          cp -r /arbre/* arbre
          cp -r /tests/* tests

      - name: Check test name
        run: ./tests/test_name
  
  test-size:
    runs-on: ubuntu-latest
    container:
      image: thibaultcne/projet_sys22
    needs: build
    steps:
      - name: Check repository
        uses: actions/checkout@v3

      - name: Build executable
        run: make

      - name: Build tests files
        run: |
          mkdir arbre
          mkdir tests
          cp -r /arbre/* arbre
          cp -r /tests/* tests

      - name: Check test size
        run: ./tests/test_size
  
  test-date:
    runs-on: ubuntu-latest
    container:
      image: thibaultcne/projet_sys22
    needs: build
    steps:
      - name: Check repository
        uses: actions/checkout@v3

      - name: Build executable
        run: make

      - name: Build tests files
        run: |
          mkdir arbre
          mkdir tests
          cp -r /arbre/* arbre
          cp -r /tests/* tests

      - name: Check test date
        run: ./tests/test_date
  
  test-regex:
    runs-on: ubuntu-latest
    container:
      image: thibaultcne/projet_sys22
    needs: build
    steps:
      - name: Check repository
        uses: actions/checkout@v3

      - name: Build executable
        run: make

      - name: Build tests files
        run: |
          mkdir arbre
          mkdir tests
          cp -r /arbre/* arbre
          cp -r /tests/* tests

      - name: Check test regex
        run: ./tests/test_regex

  test-mime:
    runs-on: ubuntu-latest
    container:
      image: thibaultcne/projet_sys22
    needs: build
    steps:
      - name: Check repository
        uses: actions/checkout@v3

      - name: Build executable
        run: make

      - name: Build tests files
        run: |
          mkdir arbre
          mkdir tests
          cp -r /arbre/* arbre
          cp -r /tests/* tests

      - name: Check test mime
        run: ./tests/test_mime
  
  test-grep:
    runs-on: ubuntu-latest
    container:
      image: thibaultcne/projet_sys22
    needs: build
    steps:
      - name: Check repository
        uses: actions/checkout@v3

      - name: Build executable
        run: make

      - name: Build tests files
        run: |
          mkdir arbre
          mkdir tests
          cp -r /arbre/* arbre
          cp -r /tests/* tests

      - name: Check test grep
        run: ./tests/test_grep

  test-dir:
    runs-on: ubuntu-latest
    container:
      image: thibaultcne/projet_sys22
    needs: build
    steps:
      - name: Check repository
        uses: actions/checkout@v3

      - name: Build executable
        run: make

      - name: Build tests files
        run: |
          mkdir arbre
          mkdir tests
          cp -r /arbre/* arbre
          cp -r /tests/* tests

      - name: Check test dir
        run: ./tests/test_dir

  test-perm:
    runs-on: ubuntu-latest
    container:
      image: thibaultcne/projet_sys22
    needs: build
    steps:
      - name: Check repository
        uses: actions/checkout@v3

      - name: Build executable
        run: make

      - name: Build tests files
        run: |
          mkdir arbre
          mkdir tests
          cp -r /arbre/* arbre
          cp -r /tests/* tests

      - name: Check test perm
        run: ./tests/test_perm

  test-name-and-size:
    runs-on: ubuntu-latest
    container:
      image: thibaultcne/projet_sys22
    needs: build
    steps:
      - name: Check repository
        uses: actions/checkout@v3

      - name: Build executable
        run: make

      - name: Build tests files
        run: |
          mkdir arbre
          mkdir tests
          cp -r /arbre/* arbre
          cp -r /tests/* tests

      - name: Check test name and size
        run: ./tests/test_name_and_size

  test-mime-and-size:
    runs-on: ubuntu-latest
    container:
      image: thibaultcne/projet_sys22
    needs: build
    steps:
      - name: Check repository
        uses: actions/checkout@v3

      - name: Build executable
        run: make
      
      - name: Build tests files
        run: |
          mkdir arbre
          mkdir tests
          cp -r /arbre/* arbre
          cp -r /tests/* tests

      - name: Check test mime and size
        run: ./tests/test_mime_and_size

