name: projet_sys22/tests

on: [push]

jobs:
  make-test:
    runs-on: ubuntu-latest
    container:
      image: racouchot/projet_sys22
    steps:
    -
      name: Build tests files
      uses: actions/checkout@v3
      run: mkdir tests
      run: cp /tests/* tests
      run: mkdir arbre
      run: cp -r /arbre/* arbre
    -
      name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: projet_sys22_tests
          path: /tests
    -
      name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: projet_sys22_arbre
          path: /arbre

  build:
    runs-on: ubuntu-latest
    steps:
    -
      name: Build
      uses: actions/checkout@v3
      run: make

  check-test-build:
    runs-on: ubuntu-latest
    needs: make-test
    steps:
    -
      name: Download artifact
      uses: actions/download-artifact@v2
      with:
        name: projet_sys22_tests
        path: /tests
    -
      name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: projet_sys22_arbre
          path: /arbre
    -
      name: Check test build
      uses: actions/checkout@v3
      run: ./tests/file_exist ftc
    -