image: racouchot/projet_sys22

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    stage: build
    before_script:
      # Copie des tests et arbre au bon endroit
      - mkdir tests
      - cp /tests/* tests
      - mkdir arbre
      - cp -r /arbre/* arbre
      - test -e make
    script:
      - Makefile
    after_script:
      - ./tests/file_exist ftc
    artifacts:
      paths:
        - ./build/findTheCat
        - ./arbre
        - ./tests

  test-arguments:
    runs-on: ubuntu-latest
    stage: test
    script:
      - ./tests/test_args
    dependencies:
      - build

  test-parkour:
    runs-on: ubuntu-latest
    stage: test
    script:
      - ./tests/test_parkour
    dependencies:
      - build

  test-name:
    runs-on: ubuntu-latest
    stage: test
    script:
      - ./tests/test_name
    dependencies:
      - build

  test-size:
    runs-on: ubuntu-latest
    stage: test
    script:
      - ./tests/test_size
    dependencies:
      - build

  test-date:
    runs-on: ubuntu-latest
    stage: test
    script:
      - ./tests/test_date
    dependencies:
      - build

  test-mime:
    runs-on: ubuntu-latest
    stage: test
    script:
      - ./tests/test_mime
    dependencies:
      - build

  test-regex:
    runs-on: ubuntu-latest
    stage: test
    script:
      - ./tests/test_regex
    dependencies:
      - build

  test-ftc:
    runs-on: ubuntu-latest
    stage: test
    script:
      - ./tests/test_grep
    dependencies:
      - build

  test-dir:
    runs-on: ubuntu-latest
    stage: test
    script:
      - ./tests/test_dir
    dependencies:
      - build

  test-perm:
    runs-on: ubuntu-latest
    stage: test
    script:
      - ./tests/test_perm
    dependencies:
      - build
