image: racouchot/projet_sys22

on: [push]

jobs:
  make-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: mkdir tests
      - run: cp /tests/* tests
      - run: mkdir arbre
      - run: cp -r /arbre/* arbre
      - run: test -e make

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: make

  check-test-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: ./tests/file_exist ftc
